FROM openjdk:17


WORKDIR /imagenDocker


RUN apt-get update && apt-get install -y git RUN git clone https://github.com/zairajazmin/appTerminalDocker.git

WORKDIR /imagenDocker/appTerminalDocker

RUN javac mensajeTerminalDocker/mensajeTerminalDocker.java

CMD ["java", "mensajeTerminalDocker.mensajeTerminalDocker"]

